In [1]:
import numpy as np
import pandas as pd


1 dimensional array

In [2]:
my_list=[1,2,3,4,5]

In [3]:
my_list

[1, 2, 3, 4, 5]

In [6]:
_ID=np.array(my_list)

In [7]:
_ID

array([1, 2, 3, 4, 5])

2 dimensional array

In [12]:
my_list_2=[[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_list_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
_2D=np.array(my_list_2)

In [15]:
_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

generate random numbers

In [18]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [19]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

steps print even num

In [20]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
steps for odd num

In [21]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

a function to generate zeros

In [22]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((10,5))#the parsing of a tuple in th form of 5col,10rows

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.ones((5,5,))*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [33]:
np.ones((4,5,))*123456

array([[123456., 123456., 123456., 123456., 123456.],
       [123456., 123456., 123456., 123456., 123456.],
       [123456., 123456., 123456., 123456., 123456.],
       [123456., 123456., 123456., 123456., 123456.]])

generate linear spaced method

In [35]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

 Generate identity matrix

In [38]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
np.random.rand(10)#float numbers

array([7.90526963e-01, 7.56916614e-01, 6.12307585e-01, 5.92385441e-01,
       1.31962456e-01, 9.33524211e-01, 7.96529034e-01, 1.01319362e-01,
       7.52161172e-04, 6.16868821e-01])

In [45]:
np.random.randint(0,500,30)#gives the start point and end point

array([233, 353, 228, 204,  45, 170, 354, 424, 210, 115, 444,   7, 399,
       462,   6,  89, 412, 463, 497,  95,  12, 134, 476,  98, 425, 429,
       386, 387, 253, 340])

In [46]:
my_arr=np.random.randint(0,30,50)

In [47]:
my_arr

array([20,  3, 19, 21, 11, 11, 14, 11,  7, 17,  9, 21,  1, 14, 19, 19, 24,
        6, 26, 24,  6, 12, 10, 28, 22, 12,  0,  6,  2, 11,  0, 15, 22, 19,
       24, 10, 11, 22, 17, 18, 22,  2, 26, 29,  4, 26,  8,  8, 29, 11])

In [49]:
my_arr.max()

29

In [51]:
np.max(my_arr)#maximum value

29

In [52]:
np.min(my_arr)

0

In [54]:
my_arr.min()

0

In [55]:
my_arr.reshape

<function ndarray.reshape>

In [56]:
my_arr.reshape(10,5)#the no. of col and rows should be divisible with the no. of values

array([[20,  3, 19, 21, 11],
       [11, 14, 11,  7, 17],
       [ 9, 21,  1, 14, 19],
       [19, 24,  6, 26, 24],
       [ 6, 12, 10, 28, 22],
       [12,  0,  6,  2, 11],
       [ 0, 15, 22, 19, 24],
       [10, 11, 22, 17, 18],
       [22,  2, 26, 29,  4],
       [26,  8,  8, 29, 11]])

In [57]:
my_arr.dtype#what the whole array holds

dtype('int32')

In [ ]:
arithmetic

In [61]:
arr=np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

addition

In [65]:
a=arr+arr

In [66]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [67]:
a+100

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120])

In [68]:
a[::2]+50

array([50, 54, 58, 62, 66, 70])

subtraction

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
a[::1]+10


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

multiplication


In [72]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
arr*12


array([  0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120])

division

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
1/0

ZeroDivisionError: division by zero

In [77]:
0/1

0.0

In [78]:
arr/arr#shows a nan in the array where there is a zero value at the begining

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [79]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

others

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
np.max(arr)

10

In [82]:
arr.max()

10

min

In [87]:
np.min(arr)

0

In [84]:
arr.min()

0

log

In [83]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

sin

In [85]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

exponent

In [86]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

slicing

In [88]:
arr_1=np.arange(11)

In [89]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr_1[::1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr_1[1:7]

array([1, 2, 3, 4, 5, 6])

In [93]:
arr_1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [94]:
arr_2=np.random.randint(0,11,20)

In [95]:
arr_2

array([ 5,  1, 10,  2,  6,  0,  5,  8, 10,  7,  3,  6,  7,  5, 10, 10, 10,
        6,  8,  9])

In [96]:
arr_3=arr_2.reshape(10,2)

In [97]:
arr_3

array([[ 5,  1],
       [10,  2],
       [ 6,  0],
       [ 5,  8],
       [10,  7],
       [ 3,  6],
       [ 7,  5],
       [10, 10],
       [10,  6],
       [ 8,  9]])

In [98]:
arr_3=arr_2.reshape(4,5)

In [99]:
arr_3

array([[ 5,  1, 10,  2,  6],
       [ 0,  5,  8, 10,  7],
       [ 3,  6,  7,  5, 10],
       [10, 10,  6,  8,  9]])

In [101]:
arr_3[1][2]

8

In [103]:
arr_3[-1][-1]#or [3]#[4]

9

In [104]:
arr_3[-4][-5]

5

In [ ]:
arr_3[]